name: Build and publish image to Docker Hub
on:
  workflow_dispatch

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: granthpai
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push images
        run: |
          docker build ./booking-service -t granthpai/booking-service:latest 
          docker push granthpai/booking-service:latest
          
          docker build ./flight-service -t granthpai/flight-service:latest
          docker push granthpai/flight-service:latest