name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'booking-service/Dockerfile'
      - 'flight-service/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: granthpai
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push booking service
        run: |
          docker build ./booking-service -t granthpai/booking-service:latest
          docker push granthpai/booking-service:latest
          
      - name: Build and push flight service
        run: |
          docker build ./flight-service -t granthpai/flight-service:latest
          docker push granthpai/flight-service:latest